services:
 fastapi:
  environment:
   DATABASE_URL: ${DATABASE_URL}
   CORS_HOST: ${CORS_HOST}
   SIGNING_KEY: ${SIGNING_KEY}
  build:
   context: Backend
   dockerfile: Dockerfile.dev
  ports:
   - 8000:8000
  volumes:
   - ./Backend:/app

 postgres:
  image: postgres:14.5-bullseye
  volumes:
   - postgres-data:/var/lib/postgresql/data
  environment:
   POSTGRES_USER: ${POSTGRES_USER}
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   POSTGRES_DB: ${POSTGRES_DB}
  ports:
   - "15432:5432"

 vite_frontend:
  image: node:lts-bullseye
  command: npm run dev
  working_dir: /app
  volumes:
   - ./Frontend:/app
  ports:
   - "3000:3000"
  environment:
   HOST_OS: ${OS}
   NODE_ENV: development
   HOST: "0.0.0.0"
   VITE_API_HOST: ${VITE_API_HOST}

volumes:
 postgres-data: {}
