services:
 fastapi:
  environment:
   DATABASE_URL: postgresql://postgres:tracking_app_password@postgres:5432/tracking_app
   CORS_HOST: http://localhost:3000
   SIGNING_KEY: ${SIGNING_KEY}
  build:
   context: Backend
   dockerfile: Dockerfile.dev
  ports:
   - 8000:8000
  volumes:
   - ./Backend:/app

 postgres:
  image: postgres:14.5-bullseye
  volumes:
   - postgres-data:/var/lib/postgresql/data
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: tracking_app_password
   POSTGRES_DB: tracking_app
  ports:
   - 15432:5432

 vite_frontend:
  image: node:lts-bullseye
  command: npm run dev
  working_dir: /app
  volumes:
   - ./Frontend:/app
  ports:
   - "3000:3000"
  environment:
   HOST_OS: ${OS}
   NODE_ENV: development
   HOST: "0.0.0.0"
   VITE_API_HOST: http://localhost:8000

volumes:
 postgres-data: {}
