version: "3.8"

services:
 fastapi:
  image: deguzmancory/backend:latest
  depends_on:
   - postgres
  environment:
   DATABASE_URL: ${DATABASE_URL}
   CORS_HOST: ${CORS_HOST}
   SIGNING_KEY: ${SIGNING_KEY}
  ports:
   - 8000:8000
  volumes:
   - ./Backend:/app

 postgres:
  image: postgres:14.5-bullseye
  volumes:
   - postgres-data:/var/lib/postgresql/data
  environment:
   POSTGRES_USER: ${POSTGRES_USER}
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   POSTGRES_DB: ${POSTGRES_DB}
  ports:
   - "15432:5432"

 vite_frontend:
  image: deguzmancory/frontend:latest
  command: /bin/bash -c "npm install @rollup/rollup-linux-x64-gnu && npm install -g npm@10.5.2 && npm run dev"
  working_dir: /app
  ports:
   - "3000:3000"
  environment:
   HOST_OS: ${OS}
   HOST_ENV: development
   HOST: "0.0.0.0"
   VITE_API_HOST: ${VITE_API_HOST}
  volumes:
   - ./Frontend:/app

volumes:
 postgres-data: {}
