# Use the Python 3.10 base image
FROM python:3.10-bullseye

# Upgrade pip
RUN python -m pip install --upgrade pip

# Install docker-compose-wait for waiting on dependencies
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

# Set working directory for the FastAPI app
WORKDIR /app

# Copy the entire app directory into the container
COPY . .

# Install project dependencies
RUN python -m pip install -r requirements.txt

# Install uvicorn
RUN python -m pip install uvicorn

# Expose port 8000 for FastAPI
EXPOSE 8000

# Command to start the FastAPI server
CMD /wait && uvicorn main:app --reload --host 0.0.0.0 --port 8000
