swagger: "2.0"
info:
  title: "Tracker App API"
  version: "1.0"
  description: "API for Tracker App"
paths:
  /hello:
    get:
      summary: "Get hello message"
      description: "Returns a hello message"
      responses:
        200:
          description: "OK"
          schema:
            type: "string"
